function T=rec_conversion(nt,nx,nz,dt,dx,dz,s1,s3,r1,r3)
N=max(length(r3),length(s3));
T=table([nt;zeros(N-1,1)],[nx;zeros(N-1,1)],[nz;zeros(N-1,1)], ...
    [dt;zeros(N-1,1)],[dx;zeros(N-1,1)],[dz;zeros(N-1,1)],...
    [s1.';zeros(N-length(s1),1)],[s3.';zeros(N-length(s3),1)], ...
    [r1.';zeros(N-length(r1),1)],[r3.';zeros(N-length(r3),1)]);
T.Properties.VariableNames={'nt','nx','nz','dt','dx','dz','s1','s3','r1','r3'};
end
